# Data
path: /kaggle/working/data
train: images/train  # train images (relative to 'path')
val: images/val  # val images (relative to 'path')

# Classes
names:
  0: general
  1: dentist

augmentations:
- Albumentations:
    blur_limit: 1
    translate: 0.1
    scale: 0.2
    shear: 0.2
    perspective: 0.1
    mosaic: 0.3
    mixup: 0.1
    brightness_contrast: 
      brightness_limit: 0.1
      contrast_limit: 0.1
    gauss_noise:
      var_limit: (10.0, 20.0)
    horizontal_flip: true
    hue_saturation:
      hue_shift_limit: 20
      sat_shift_limit: 50
    rotate:
      limit: 30
      p: 0.7